### ISSUE TITLE
이메일 스타일 개선

### ISSUE THREAD

**Issue by dalikim** [parti-coop/catan-web#204]

**Comment by berry502** [comment]
@hobread-ufo @dalikim https://drive.google.com/drive/folders/0B1fCwOawxIhHSTBCcXMwbG9kblk 메일링, 멘션, 비밀번호 재설정은 제가 임의로 후다닥. 한 부분이 있어서. 웹에 쓰인 컴포넌트를 그대로 붙이긴 했는데 빠진 것 있거나 디자인으로 수정봐야할 부분은 선화님 작업 전에 미리 알려주세요.

**Comment by dalikim** [comment]
미룹니다.
