### ISSUE TITLE
링크 작성 후 화면에서 링크 제목이 바로 안 읽히는 현상 해결

### ISSUE THREAD

**Issue by luluv** [parti-coop/catan-web#216]

**Comment by dalikim** [comment]
바로 해결해야할 우선순위 높은 문제일까요? 
아니면 로딩 중이라고 나오면 될까요? 

현재는 슬랙처럼 링크 넣고 한참 후에 링크 제목을 읽어오는지라 그렇습니다만. @luluv

**Comment by luluv** [comment]
일단 로딩중이라는 안내 문구만 들어가도 괜찮을 것 같습니다. 

저는 항상 한 번 새로고침을 해서 제목으로 바뀌는 걸 확인하고 있는데, 다른 사람들에게는 오류로 느껴질것 같아서요.  @dalikim
