### ISSUE TITLE
프로필 수정시 오류 메시지 수정

### ISSUE THREAD

**Issue by luluv** [parti-coop/catan-web#226]
프로필 수정시에 나오는 오류메시지를 읽기 편하게 개선하면 좋겠습니다.

**Comment by dalikim** [comment]
@luluv 어떤 점이 불편하고 어떻게 개선하면 좋을까요?

**Comment by luluv** [comment]
![2016-05-24 4 44 34](https://cloud.githubusercontent.com/assets/17918439/15496173/ded2c2ea-21ce-11e6-8b09-631e9fcf1bc5.png)

**Comment by luluv** [comment]
'형식이 올바르지 않습니다.'라는 오류 메시지가 너무 불친절해서요. 
'아이디를 한글로 작성해주세요' 혹은 '이미 사용 중인 아이디입니다' 이런 걸로 바꾸면 좋겠습니다 @dalikim

**Comment by dalikim** [comment]
@luluv 넵. 아이디가 안뇽이군요 ㅎㅎ 영어만 된다는 레이블도 적어야겠네요.

**Comment by luluv** [comment]
넵. 친절한 빠띠 ㅎㅎ
