### ISSUE TITLE
자료 탭에서 링크 삽입시, 링크에 대한 이미지와 제목, 본문내용을 편집할 수 있게 해주세요.

### ISSUE THREAD

**Issue by luluv** [parti-coop/catan-web#287]
http://parti.xyz/articles/920

모달에서 보여지는 링크 제목, 이미지, 내용이 수정가능한 영역이었으면 좋겠습니다.

**Comment by luluv** [comment]
- 제목 : 필요한 경우에, 사람들에게 더 와닿는 키워드 단어들로 조합하여, 구글 검색에도 잘 걸리고, 사용자들에게 전달력도 높이고 싶습니다. 빠띠를 주도적으로 쓰게 될 분들(액션그룹)에게도 필요한 기능이 아닐까 싶어요.
- 이미지 : 링크의 글 안에 이미지가 여러장인 경우, 전달력 높은 이미지를 보여주도록 선택하고 싶습니다.
- 본문내용 : 현재는 본문의 첫부분이 네줄정도 나오고 갑자기 끊깁니다. 그래서 링크를 클릭해보고 싶은 마음이 들지 않아요. 본문의 글을 요약하는 내용이 보여지도록 편집되면 사람들로 하여금 링크 클릭율도 높일 수 있을 것 같습니다. 링크를 클릭하지 않을 때의 본문에 대한 이해도를 높일 수 있어서 댓글 참여율도 높일 수 있을 것 같구요.

**Comment by dalikim** [comment]
누가 편집하느냐의 문제가 있습니다. 링크란게 어느 누구의 소유도 아니거든요. 그래서 빠띠메이커가 등장하기 전까지 방법이 없었습니다. 

하면서 그들이 편집하면 어떨까 하는데 의견 주세요

**Comment by luluv** [comment]
빠띠 메이커들이 편집하게 하는 것, 좋습니다. 
지금 빠띠 메이커로 등록되어 계신 분들이 자신이 메이킹하는 빠띠에서는 링크를 걸 때 편집이 가능하도록 기능이 생기면 좋겠습니다.
