### ISSUE TITLE
비공개 그룹에 초대됐을 때 그룹에서만 초대한 경우, 해당 그룹홈에 접속할 수 없습니다. 

### ISSUE THREAD

**Issue by dalikim** [parti-coop/catan-web#384]
또한 그룹홈에 접속할 수 없어 채널 가입도 초대가 아닐 경우 불가능합니다.

**Comment by dalikim** [comment]
재현할 방법을 찾고 있습니다.

제가 시도한 방법은 아래와 같고요. 위의 상황이 재현되지 않아서 개발할 수 없는 상황이네요. 도움 부탁드립니다.

1. 테스트 직전 상태입니다. @달리라는 그룹 오거나이저 멤버가 비공개 그룹의 회원 탭에서 접속하여 미가입자 @blue_spider를 찾아 본 결과입니다.  @blue_spider가 없습니다.
<img width="1130" alt="스크린샷 2019-09-07 09 29 44" src="https://user-images.githubusercontent.com/1650024/64467480-ea01fb80-d153-11e9-96b2-24405cf212b6.png">

2. 역시 테스트 직전입니다. 미가입자 @blue_spide가 해당 그룹의 첫화면에 접속하면 이렇게 보입니다.
<img width="1071" alt="스크린샷 2019-09-07 09 29 55" src="https://user-images.githubusercontent.com/1650024/64467435-7b24a280-d153-11e9-8ef6-bd56a28d9bf9.png">

3. 테스트를 시작합니다. @달리가 @blue_spide를 초대합니다.
<img width="993" alt="스크린샷 2019-09-07 09 30 25" src="https://user-images.githubusercontent.com/1650024/64467447-9394bd00-d153-11e9-813d-11aa7f5742bd.png">

4. 초대가 잘 되었습니다.
<img width="1096" alt="스크린샷 2019-09-07 09 30 40" src="https://user-images.githubusercontent.com/1650024/64467455-9e4f5200-d153-11e9-8126-1f391e31e43c.png">

5. @blue_spide가 다시 해당 그룹을 접속해 봅니다.
<img width="1057" alt="스크린샷 2019-09-07 09 31 06" src="https://user-images.githubusercontent.com/1650024/64467464-bb842080-d153-11e9-81e3-6e43e1bebf32.png">


제가 처음 이 보고를 받았을 때는 5번 과정에서 오류가 있거나 2번 화면처럼 보이리라 생각했습니다. 하지만 재현되지 않았습니다. 도움을 기다리겠습니다.

**Comment by dalikim** [comment]
@anne-parti @zoointhezoo 요 이슈 한 번 검토 부탁드립니다.

**Comment by anne-parti** [comment]
테스트를 위해 달리님 계정을 '안나 테스트2' 그룹에 초대했어요. 어떻게 보이는지 알려주세요. 
저의 경우에는 이렇게 보입니다. 

해당 그룹
- 생성 후 별도 채널 만들지 않음
- 기본 채널 (일반채널, 잡담) 외 별도 채널 추가하지 않음

1. 오거나이저
- 목록에서 채널 홈과 모든 채널이 확인/ 접속 가능합니다.
<img width="254" alt="organizer" src="https://user-images.githubusercontent.com/55128558/65310244-e09f7700-dbc8-11e9-9c50-b770aa9830ad.png">

2. 멤버
- 채널 홈, 채널 확인/ 접속 불가능
- 채널 만들기만 가능합니다. 
<img width="256" alt="member" src="https://user-images.githubusercontent.com/55128558/65310366-23f9e580-dbc9-11e9-9551-34c81d4a382c.png">

**Comment by dalikim** [comment]
@anne-parti 아 재현 성공이고 버그는 맞네요. 

다만 제가 버그 리포트 독해에 오해를 했어요. 버그 리포트 "그룹홈에 접속할 수 없어"라고 하는게 "그룹홈에 권한 등의 이유로 접속 불가"란 뜻으로 읽혔습니다. 그게아니라 "가입된 채널이 없을때 해당 그룹의 그룹홈 접속 링크가 사이드 바에 표시되지 않음"이죠? ^^ 저는 그룹을 "검색"해서 들어가니 홈에 접속이 되었거든요.

이런 커뮤니케이션 미스의 상황이 맞는지요? 그렇다면 좀더 커뮤니케이션 방식을 개선할 방법이 있을까요? 그냥 제가 잘 읽으면 될지도 모르지만요

**Comment by anne-parti** [comment]
앞으로는 오류 상황에 대해서 더 자세히, 가능하면 스크린샷까지 첨부하도록 할게요. 
해당 기능 이제 정상적으로 작동합니다.

**Comment by dalikim** [comment]
@anne-parti 아이고 감사합니다. 앞으로 자주 이야기하면 되겠죠 ^^

**Comment by dalikim** [comment]
@gjkimpam 이것도 닫아요. 테스트 해보시고 테스트 필요 레이블 떼어 주세요.

**Comment by gjkimpam** [comment]
> @gjkimpam 이것도 닫아요. 테스트 해보시고 테스트 필요 레이블 떼어 주세요.

네, 제가 방금 [안나 님의 방법](https://github.com/parti-coop/catan-web/issues/384#issuecomment-533454695)으로 확인했을 때, 
멤버의 경우, '그룹 홈'이 노출되었어요. '모든 채널'을 클릭했을 경우 '일반 채널'과 '잡담' 채널에 가입할 수 있었습니다.  
<img width="241" alt="스크린샷 2019-09-29 오후 12 34 42" src="https://user-images.githubusercontent.com/35594166/65825751-c09d4100-e2b5-11e9-8d4f-47f48d0fc60e.png">
