### ISSUE TITLE
위키를 아카이브하면 접어서 볼때도 아카이브된 위키인지 표시가 나야합니다.

### ISSUE THREAD

**Issue by dalikim** [parti-coop/catan-web#385]
지금은 아무 표시가 나지 않습니다. 제목 앞에 라벨이나 아이콘을 다는 것도 고려해 봄직합니다.

**Comment by anne-parti** [comment]
위키 아카이브 하면 아카이브 되면서 위키 펼쳐진 상태로 제목 우측에 "아카이브" 라벨이 추가되는데요.
위키 접어보기 할 경우 아카이브 라벨이 사라집니다. 펼쳐보기 하면 다시 나타나구요. 

<접어보기> -- 라벨 안보임
<img width="647" alt="wiki_archive_01" src="https://user-images.githubusercontent.com/55128558/65301702-88aa4580-dbb3-11e9-84b9-52f23be1fdb3.png">

<펼쳐보기> -- 펼칠 경우 라벨 보임
<img width="649" alt="wiki_archive_02" src="https://user-images.githubusercontent.com/55128558/65301722-96f86180-dbb3-11e9-83d3-e7364375d0ce.png">

**Comment by dalikim** [comment]
라벨을 바꿔 놓겠습니다.

**Comment by anne-parti** [comment]
정상적으로 동작합니다.

**Comment by dalikim** [comment]
이것도 우선 닫을께요 @gjkimpam

**Comment by dalikim** [comment]
테스트 필요 레이블은 유지합니다. @gjkimpam 님이 떼주세요.
