### ISSUE TITLE
게시물의 북마크에서 태그를 달때 태그 이름이 길 경우 태그박스 UI가 깨집니다.

### ISSUE THREAD

**Issue by dalikim** [parti-coop/catan-web#387]
X 버튼만 하단으로 내려가네요.

**Comment by zoointhezoo** [comment]
아주 길게 쓸 일은 거의 없겠지만 아~주 길게 쓸 경우 깨지긴 하네요. 차후에 정해진 글자수 초과 시(max 40자 정도?) 입력 불가능하도록 글자수 제한을 두는 것도 좋겠습니다.

**Comment by dalikim** [comment]
40자 정도가 좋네요. 오늘내일 바로 적용해 볼께요.
