### ISSUE TITLE
가입 중에 개인정보처리방침 페이지를 확인한 경우, 가입이 완료되었을 때 개인정보처리방침 페이지로 돌아가는 버그가 있습니다.

### ISSUE THREAD

**Issue by dalikim** [parti-coop/catan-web#392]
로그인 전에 방문한 마지막 페이지를 기억하고 해당 페이지로 돌아갑니다.
가입 중에 개인정보처리방침 페이지를 마지막으로 확인한 경우인데요. 위 규칙에 따라 개인정보처리방침 페이지를 로그인 후 첫 페이지로 보여지게 되네요. 많이 어색합니다.

**Comment by anne-parti** [comment]
지금 테스트 서버에 개인정보 처리방침 페이지 확인 후 로그인 시 개인정보 처리방침 페이지로 이동하나요? 저는 재현이 안됩니다. 신규가입 시 아래와 같이 동작하고 있어요. 

1. 이메일로 가입
- 가입단계에서 개인정보 처리방침 확인 → 개인정보 페이지 새 창으로 뜸
- 가입 완료 시 이메일 인증 요청 토스트 메시지 뜸
- 이메일 인증 후 로그인 시 메인 페이지로 이동

2. 소셜 계정으로 가입
- 별도 개인정보 처리방침 동의 단계 없음 
- 가입 시 관심사 선택 페이지로 이동

**Comment by dalikim** [comment]
네 재현되면 안됩니다. 맨 처음 댓글에 적었다시피 "로그인 전에 방문한 마지막 페이지를 기억하고 해당 페이지로 돌아간다"라는 로직이 원래 것이었습니다. 그랬더니 "가입 중에 개인정보처리방침 페이지를 마지막으로 확인한 경우, 이 로직 따라 개인정보처리방침 페이지를 로그인 후 첫 페이지로 보여지기"가 실현되었습니다.

이를 교정보았습니다. @anne-parti

**Comment by anne-parti** [comment]
넵 그렇다면 지금은 의도한대로 동작하네요. 지금 구현된 방법이 자연스럽고 좋아 보여요. 클로즈 처리하겠습니다.

**Comment by dalikim** [comment]
교정은 단순합니다. 개인정보처리방침 페이지를 방문한 경우 "로그인 전에 방문한 마지막 페이지를 기억하기" 로직을 회피하도록 하였습니다. @anne-parti
