### ISSUE TITLE
광고 메일 수신 여부를 가입 절차 당시에 체크할 수 있게 합니다.

### ISSUE THREAD

**Issue by dalikim** [parti-coop/catan-web#393]

**Comment by dalikim** [comment]
@gjkimpam 당장 광고 메일 수신 여부가 필요할까요? 빙글이나 트위터 같은 어디에도 그런게 없는데요.

**Comment by rest515** [comment]
저도 바로 필요하지 않은 기능으로 보이네요.

**Comment by dalikim** [comment]
@kninami @zoointhezoo 님의 의견은 어떠세요?

**Comment by gjkimpam** [comment]
#395 이슈와 엮여있다고 생각해요. 
저희가 광고, 서비스 목적을 분리하면 판단할 수 있을 것 같은데요. 가입 당시에 수신 여부를 설정할 수 있게 하면 좋겠어요. 
https://github.com/parti-coop/catan-web/issues/395#issuecomment-529491594

**Comment by dalikim** [comment]
@gjkimpam 제 생각을 정리하면 이래요.

- 당분간은 광고 목적으로 메일 드리지 않으면 좋겠다. 광고 전략이 필요하지는 않다. 그런 메일 있다면 빼도 무방하다. 못뺀다면 광고 메일이 아니라는 반증이다.
- 광고 메일 드릴 전략이 세워지면 그때 넣자.

**Comment by dalikim** [comment]
@gjkimpam @anne-parti 더 이야기 진행 안되면 닫아 놓을께요.
