### ISSUE TITLE
가입 후 이메일이 맞는지 확인하는 팝업창이 뜨는데요. 더이상 필요없는 절차입니다. 이 절차를 삭제합니다.

### ISSUE THREAD

**Issue by dalikim** [parti-coop/catan-web#394]

**Comment by gjkimpam** [comment]
팝업창이 오류없이 삭제되어 뜨지 않습니다.

**Comment by anne-parti** [comment]
이메일 주소로 가입 → 이메일 인증 완료 → 로그인 시 자주 사용하는 이메일인지 확인하기 위해 띄웠던 보라색 창이 안떠야 하는거죠? 저는 테스트 서버에서 이메일로 가입 시 인증 메일이 안와서 확인이 불가능합니다

**Comment by anne-parti** [comment]
찐쩐님이 알려주셔서 확인했고 클로즈하겠습니다~!
