### ISSUE TITLE
가입할 때 각종 메일 수신 여부를 옵트아웃으로 합니다.

### ISSUE THREAD

**Issue by dalikim** [parti-coop/catan-web#395]

**Comment by dalikim** [comment]
이건 고민됩니다. 많은 서비스가 알림 메일은 옵프인으로 압니다. 제가 잘못 알고 있나요?

**Comment by dalikim** [comment]
@gjkimpam 님은 어떻게 생각하세요?

**Comment by gjkimpam** [comment]
> @gjkimpam 님은 어떻게 생각하세요?
네, 서비스 대부분이 옵트인이죠.

지난번 개인정보처리방침 교육에 의하면 
parti.xyz의 개인정보취급방침에서 '1. 개인정보의 이용 목적'  
> 마케팅 및 서비스 분석과 개선 
>정보 전달 및 마케팅, 광고 등에 사용되며, 회원의 서비스 이용에 대한 통계, 이를 통한 맞춤형 서비스 제공과 서비스 개선에도 사용됩니다.

항목에 따라 사용자가 메일 수신을 동의한 것으로 간주하고 발송해도 되는지 여쭈었는데요. 
❌→ 안 됩니다. 1. 명시적으로 동의 여부를 물어보고 2. (서비스 가입자가) 체크하게 해야 합니다.

그래서 옵트아웃으로 변경하는 것이 좋다고 생각해요.

**Comment by dalikim** [comment]
@gjkimpam 광고 목적이냐 서비스의 목적이냐에 따라 다를 것이라고 생각되요. 옵트아웃 일률적으로 적용하는데 고민이 있습니다.

**Comment by gjkimpam** [comment]
슬로워크분들과 개인정보 처리 관련해 나눴던 내용을 정리해볼게요. 

광고성 소식인지 목적을 분류할 수 있는 기준은 서비스 이용에 어떤 영향을 주느냐에 따라 구분할 수 있음.
**목적 분류**
광고 목적 
- 소식을 읽지 않아도 서비스 이용에 이상이 없으면 마케팅 목적
- 예) 신규 기능 출시, 버전 업그레이드, 오프라인 이벤트 개최 

서비스 목적
- 소식을 전달하지 않았을 때 사이트 이용에 문제가 생기는 것
- 서비스 이용에 필수인 내용
- 예) 서비스 약관 변경, 00 소셜로그인 기능 지원 안함

그리고 
광고성 목적인 메일 발송시에, 
- 하단에 수신거부 가능한 푸터를 삽입(수신자가 앞으로 이런 소식에 대한 수신을 선택할 수 있는거죠)
- 발송 주체가 유한회사 빠띠라면 제목에 (광고)를 붙여야 하고, 사회적협동조합 빠띠라면 (대체로) 광고 안 붙여도 됩니다.

**Comment by gjkimpam** [comment]
저희는 현재 다섯 가지 이메일을 보내는데요. 
1. 나를 멘션한 게시글이나 댓글을 이메일로 받습니다.
2. 공지를 이메일로 받습니다.
3. 설문이나 투표의 진행 사항을 이메일로 받습니다.
4. 오거나이저인 채널에 신규 멤버가 가입한 경우 이메일을 받습니다.
5. 요약된 빠띠 소식을 이메일로 받습니다.

위 다섯 가지 소식을 받지 않아도 서비스 이용에는 무리가 없기에 서비스 목적은 아닌 것 같아서, 
옵트아웃으로 해야되지 않을까 싶어요.

**Comment by dalikim** [comment]
1. 나를 멘션한 댓글을 놓치면 협업에 문제가 발생합니다.  이걸 놓치지 않게 잘 설계하여 알려주지 않으면 협력을 위한 그룹스 서비스 이용에 문제가 발생합니다.
2. 공지도 마찬가지입니다.
3. 설문도 마찬가지입니다.
4. 신규멤버도 마찬가지입니다.
5. 요약도 마찬가지입니다.

**Comment by dalikim** [comment]
@gjkimpam @anne-parti 더 진행 안되면 우선 닫겠습니다.
