### ISSUE TITLE
내 홈 페이지의 오른쪽 사이드바에 게시글 수와 댓글 수를 숫자로 만이 아닌 한글과 섞어서 표시합니다.

### ISSUE THREAD

**Issue by dalikim** [parti-coop/catan-web#397]
<img width="967" alt="스크린샷 2019-09-07 09 49 20" src="https://user-images.githubusercontent.com/1650024/64467591-e1f68b80-d154-11e9-8955-d5aba6521831.png">

**Comment by gjkimpam** [comment]
/dashboard 에서 숫자+댓글 병행 표기된 것 확인했습니다.

**Comment by gjkimpam** [comment]
- [ ] 게시글-댓글 사이의 간격이 그룹-게시글 간격만큼 널찍이 있으면 숫자별 구분이 되어 좋을 것 같아요. 큰 이슈는 아니니 이번에 반영되지 않아도 좋습니다.

**Comment by anne-parti** [comment]
작성 게시글/댓글 수가 작아서 확인이 불가능합니다. @gjkimpam 님이 다시 한 번 확인하시고 클로즈 해주세요.

**Comment by gjkimpam** [comment]
> 작성 게시글/댓글 수가 작아서 확인이 불가능합니다. @gjkimpam 님이 다시 한 번 확인하시고 클로즈 해주세요.

네, '숫자+천'으로 뜨는 것 확인했습니다.
