### ISSUE TITLE
위키를 아카이브할때, 현재 로그인해서 아카이브한 사람이 아닌 최초 위키를 만든 사람이 아카이브 한 것으로 표시됩니다.

### ISSUE THREAD

**Issue by dalikim** [parti-coop/catan-web#398]

**Comment by gjkimpam** [comment]
위키 아카이브 후, 제가 아카이브 한 것으로 뜹니다. 
안내문 _'내가 위키를 아카이브했습니다.'_

**Comment by dalikim** [comment]
> 위키 아카이브 후, 제가 아카이브 한 것으로 뜹니다.
> 안내문 _'내가 위키를 아카이브했습니다.'_

@gjkimpam 그래서 예상과 이치하여 성공한 것인가요? 아니면 예상과 달라 실패한 것인가요? 좀더 자세하게 써주세요.

**Comment by gjkimpam** [comment]
> > 위키 아카이브 후, 제가 아카이브 한 것으로 뜹니다.
> > 안내문 _'내가 위키를 아카이브했습니다.'_
> 
> @gjkimpam 그래서 예상과 이치하여 성공한 것인가요? 아니면 예상과 달라 실패한 것인가요? 좀더 자세하게 써주세요.

성공적으로 뜹니다. 
이 테스트의 요지는 제가 로그인하여 위키 아카이브 할 경우, 제가 한 것으로 뜨는 걸 확인하는 것으로 생각했어요. 오류이거나 이슈가 발견될 경우 '오류' 혹은 '이슈라고 좀더 분명히 써둘게요.

**Comment by anne-parti** [comment]
저도 의도대로 로그인한 유저가 아카이브 한 것으로 뜹니다. 클로즈 처리 할게요.
