### ISSUE TITLE
게시물 북마크에 태그 추가 시, 글자수를 제한합니다. 

### ISSUE THREAD

**Issue by anne-parti** [parti-coop/catan-web#399]
#387 

북마크에 태그를 추가할 때, 아주 길게 추가할 경우 
1. 게시글 목록에서 태그 내용 전체를 확인할 수 없거나
2. 내 홈 > 북마크에서 X 버튼이 노출되지 않아 태그를 제거할 수 없습니다. 

<img width="706" alt="tag" src="https://user-images.githubusercontent.com/55128558/64592298-a2df6900-d3e6-11e9-9f51-545cf5c4a868.png">

태그 추가 시 일정 글자수(PC/ 모바일 화면 너비 고려) 초과 입력 시 입력 안되도록 글자수 제한 기능 추가가 필요합니다.

**Comment by dalikim** [comment]
40정도 좋습니다. 오늘 내일 바로 적용해 볼께요.

**Comment by dalikim** [comment]
@anne-parti 40자면 모바일에서 폭이 너무 넓네요. 우선 15자로 제한해서 출시하면 어떨까요?

**Comment by anne-parti** [comment]
1. 채널에서 북마크 + 태그 입력시에 모두 정상적으로 동작합니다. 
2. 내 홈 > 북마크에서 태그 추가 시에 입력 시에 길게 입력하면 뒤쪽이 보이지 않는데요. 입력 할 때 커서 따라 뒤쪽으로 이동하도록 수정 부탁드립니다. (마지막 글자 2 뒤로 텍스트를 입력해도 어떤 글자를 입력 중인지 보이지 않습니다. 스크린샷 참조)
![image](https://user-images.githubusercontent.com/55128558/65660281-35c80680-e069-11e9-9e24-17a234b3414e.png)

**Comment by dalikim** [comment]
@anne-parti @gjkimpam 테스트 부탁드립니다.

**Comment by gjkimpam** [comment]
> @anne-parti @gjkimpam 테스트 부탁드립니다.

1. 정상적으로 태그를 입력할 때 커서 따라 뒤로 입력하는 것 확인했습니다. 
2. 정상적으로 15글자로 제한되는 것 확인했습니다.

**Comment by anne-parti** [comment]
확인하고 클로즈합니다.
