### ISSUE TITLE
테스트를 위해 개발 서버에서 탈퇴 시뮬레이션을 할 수 있습니다.

### ISSUE THREAD

**Issue by dalikim** [parti-coop/catan-web#401]

**Comment by dalikim** [comment]
@anne-parti 님
지금은 탈퇴한 유저의 닉네임을 재사용할 수 없게 막혀있습니다. 혹시 그 이유로 동일 아이디 사용이 안되는 것 아닐까요?

탈퇴한 유저의 닉네임을 재사용 금지 정책의 이유는 이렇습니다. 혹시 모를 운영 상 곤란함이 있을까봐 데이터베이스에 해당 유저가 탈퇴하면 글을 삭제 표기만 하고 실제 지우지 않거든요. 

그리고 조만간 이 정책에 대해서 논의해야합니다. 3개월 정도야 상관없는데 지우긴 해야할거거든요.

**Comment by anne-parti** [comment]
1. 사용자 탈퇴 시 해당 사용자가 남겼던 글이 모두 삭제되나요? (저는 안된다고 알고 있었어요. 사용자가 명시적으로 삭제하지 않았다면 탈퇴 후에도 글이 남아있는게 좋지 않을까요? )
2. 일정 기간 후 사용자 정보 지우는 데는 동의합니다. 그 기간에 대해서는 논의가 필요하겠네요. 
3. 탈퇴 시뮬레이션 후에도 가입 절차 없이 동일 아이디/ 비밀번호로 로그인이 가능한데요. 시뮬레이션이라 깨끗하게 탈퇴처리가 되지 않기 때문인가요?

**Comment by dalikim** [comment]
1. 현재는 사용자 탈퇴 시 해당 사용자가 남겼던 글이 모두 삭제처리하고 있습니다. 저도 사용자가 명시적으로 삭제하지 않았다면 탈퇴 후에도 글이 남아있는게 맞다고 생각합니다. 제 생각엔 잘못된 것이고요. 일종의 부채(빚)입니다. 

이것과 관련된 것은 사용자가 스스로 자신의 글을 일괄 삭제하고 싶은 방법을 제공 못하고 있는 점도 문제예요. 저는 이게 아주 중요한 기능이라고 생각합니다만 우선순위가 자꾸 밀리는 일이예요. 그래서 궁여지책으로 탈퇴요청 시 글도 삭제해 드리고 있습니다. 

예전에 탈퇴가 두 달에 한 두 건이라 그나마 유야무야 넘어갔는데요. 요즘 탈퇴가 한 달에 3 명 정도로 올라가고 있네요. 걱정입니다.

2. 2.9.0 기획에 탈퇴 사용자 정보 3개월 이후 삭제 올렸습니다. https://union.parti.xyz/posts/30449

3. 요건 한 번 함께 공동 페어해서 재현해 보면 좋겠습니다.

**Comment by dalikim** [comment]
@anne-parti @gjkimpam 이것 마일스톤을 2.9.0으로 옮길께요. 아주 급한 사항은 아니라 봅니다.

**Comment by gjkimpam** [comment]
> @anne-parti @gjkimpam 이것 마일스톤을 2.9.0으로 옮길께요. 아주 급한 사항은 아니라 봅니다.

좋습니다. 2.9.0 위키 남겨주신 것에 저도 간단히 의견 남겨놓았어요.
