### ISSUE TITLE
채널 휴면 전환하기 선택 시 '권한 없습니다' 오류 메시지가 뜹니다. 

### ISSUE THREAD

**Issue by anne-parti** [parti-coop/catan-web#402]
채널 설정 > 채널 휴면하기 > 휴면 전환하기 버튼 클릭 시 '권한이 없습니다' 메시지가 표시된 후 채널 홈으로 전환되어 휴면 설정이 불가능합니다.

**Comment by anne-parti** [comment]
1. 휴면 채널 설정 시 다른 채널에서 등록한 관련 채널 목록(우측 사이드바)에서 사라지지 않고 '채널명+휴면 아이콘'으로 표시됩니다.
2. 휴면 채널 설정 시에도 검색 결과에 포함됩니다.

**Comment by dalikim** [comment]
@anne-parti @gjkimpam 테스트 부탁드립니다.

**Comment by gjkimpam** [comment]
> 1. 휴면 채널 설정시 다른 채널에서 등록 된 관련 채널 목록 (우측 채널 바)에서 사라지지 않은 '채널명 + 휴면 아이콘'으로 표시됩니다.
> 2. 휴면 채널 설정시에도 검색 결과가 포함됩니다.

저도 (오거나이저가 아닌 상태에서) 테스트 했을 때 안나 님과 유사한 결과가 나왔어요. 

휴면 채널로 설정하고 나서 로그아웃 후 
* '쿱 사진'을 검색했을 때 왼쪽 메뉴바에 뜨더라고요. 
<img width="239" alt="스크린샷 2019-09-29 오후 12 17 49" src="https://user-images.githubusercontent.com/35594166/65825596-c42fc880-e2b3-11e9-8226-251235fda1ba.png">

* 로그아웃을 하고 '쿱사진'을 검색했을 때 검색 결과로 아래와 같이 나왔어요. 
<img width="239" alt="스크린샷 2019-09-29 오후 12 17 49" src="https://user-images.githubusercontent.com/35594166/65825580-7f0b9680-e2b3-11e9-9817-6b1fd3d46f7e.png">

**Comment by dalikim** [comment]
@gjkimpam 오거나이저여서 그런 결과가 나온건지 확인해 주셔요

**Comment by gjkimpam** [comment]
> @gjkimpam 오거나이저 여서 그런 결과가 나오는 건지 아닌 주셔요

시크릿창에서 로그인 안 하고(오거나이저가 아닌 상태) 테스트했을 때도 '쿱사진'이 검색됐어요.  
<img width="1280" alt="스크린샷 2019-09-29 오후 12 44 09" src="https://user-images.githubusercontent.com/35594166/65825852-e37c2500-e2b6-11e9-871f-03318a0613f3.png">

**Comment by anne-parti** [comment]
저는 달리님이 설명해주신대로 동작합니다. 
찐쩐 @gjkimpam 님 다시 한 번 확인 부탁드려요. 

---
비공개 그룹에서 테스트 했습니다. 

### 오거나이저
1. 휴면 채널에 남긴 글이 검색 됩니다. 
- 채널 검색 결과에 목록에서 채널 이름 옆에도 zZ 가 표시되면 어떨까요? (스크린샷의 '일반 채널' 옆에)
<img width="330" alt="deactivated" src="https://user-images.githubusercontent.com/55128558/65885198-259b8880-e3d5-11e9-8ed6-6560d2a7da24.png">
2. 우측 사이드바 관련 채널에 휴면 채널이 표시되지 않습니다.

### 멤버
1. 휴면 채널에 남긴 글이 검색되지 않습니다. 
2. 우측 사이드바 관련 채널에 휴면 채널이 표시되지 않습니다.

**Comment by gjkimpam** [comment]
확인했습니다. 정상 작동합니다. 
> 비공개 그룹에서 테스트 했습니다.
> 
> ### 오거나이저
> 1. 휴면 채널에 남긴 글이 검색 됩니다.
> 
> * 채널 검색 결과에 목록에서 채널 이름 옆에도 zZ 가 표시되면 어떨까요? (스크린샷의 '일반 채널' 옆에)
**저도 이 아이디어 좋습니다 @찐쩐**
> <img alt="deactivated" width="330" src="https://user-images.githubusercontent.com/55128558/65885198-259b8880-e3d5-11e9-8ed6-6560d2a7da24.png">
> 
> 2. 우측 사이드바 관련 채널에 휴면 채널이 표시되지 않습니다.
> ### 멤버
> 1. 휴면 채널에 남긴 글이 검색되지 않습니다.
> 2. 우측 사이드바 관련 채널에 휴면 채널이 표시되지 않습니다.
**저도 오거나이저, 멤버로 각각 테스트했을 때 안나님이 얘기하신 것처럼 나왔어요.
