### ISSUE TITLE
채널 내 폴더 탭에서 글 목록 클릭 시 글로 이동하지 않음

### ISSUE THREAD

**Issue by anne-parti** [parti-coop/catan-web#403]
기존 버전에서 채널 > 폴더 탭에서 글 제목(목록) 클릭 시 기존에는 해당 글 상세 페이지로 이동했는데요. 
지금은 클릭해도 아무 동작이 없습니다. 클릭 시 해당 글 상세 페이지로 이동하도록 수정해주세요.

**Comment by anne-parti** [comment]
정상적으로 동작합니다.

**Comment by dalikim** [comment]
@gjkimpam 님 테스트가 없지만 완료하고 닫을께요. 혹시 문제 발견되시면 다시 열어주세요.
