### ISSUE TITLE
그룹 홈 로딩 속도를 향상합니다.

### ISSUE THREAD

**Issue by iamswain25** [parti-coop/catan-web#415]
그룹스에 다른 기능보다 사용성에 가장 영향을 끼치는 속도 개선이 필요하다 싶습니다.
어렵겠지만 목표를 3초 이내로 잡는게 어떨까 싶네요.

![](https://www.hostingmanual.net/wp-content/uploads/website-speed-3seconds.png)

저는 항상 첫 url 을 https://union.parti.xyz/ 로 접속하는데 이 메인페이지라도 로직을 단순화시키는게 어떨까 싶습니다.

아마 미국이라서 더 느릴것 같은데, 한국에서는 속도가 얼마나 나올지 모르겠네요.
캐시 없애고 처음 로딩하면 19.79초가 걸리고

![Screenshot from 2019-12-07 17-12-34](https://user-images.githubusercontent.com/15191725/70383372-d0727a80-1921-11ea-994f-7fed39adf90a.png)

캐시 활용해서 로딩하면 9초가 걸립니다.

![Screenshot from 2019-12-07 18-38-25](https://user-images.githubusercontent.com/15191725/70383355-462a1680-1921-11ea-8ab4-2a3a9aa8a52a.png)

참고로 사이트 내부에서 AJAX 요청 시 1.7초 걸리고
다른 화면 이동 시 평균 4~5초가 걸립니다.

**Comment by dalikim** [comment]
1. 내용에 맞춰 제목을 수정해도 될까요? 말씀대로 모든 페이지를 속도 조절하자는건 현실적이지 않습니다.  
2. 그리고 실제 사용자가 인지적으로 Finish가 아니라 Load 시점으로 압니다. http://www.theasta.net/blog/2012/06/23/three-key-moments-web-performance/ 요건 의견을 나눠보면 좋겠네요. 목표 수치를 맞추면 해서요. @iamswain25

**Comment by dalikim** [comment]
@iamswain25 제목을 바꿔보겠습니다.
