### ISSUE TITLE
댓글 사진 업로드/ 게시 버튼이 보이지 않습니다.

### ISSUE THREAD

**Issue by iamswain25** [parti-coop/catan-web#424]
![Screenshot from 2020-01-08 15-28-50](https://user-images.githubusercontent.com/15191725/71955447-b4693e00-322b-11ea-99e8-9d464c730ee2.png)

> 100%일때 보이지 않고,
> 줌을 70%까지 줄이면 보입니다.

확인 결과 댓글 타이핑을 하면 밑에 보이네요. 댓글을 사진 첨부 후에 넣으려니 이와 같은 현상이 나타납니다.

**Comment by dalikim** [comment]
의도된 것으로 완료 처리합니다
