### ISSUE TITLE
멘션이 아닌 조건으로 알림을 한 번 받은 후에 해당 글이나 댓글을 수정해서 멘션이 되면 멘션 목록 페이지에서는 누락됩니다.

### ISSUE THREAD

**Issue by iamswain25** [parti-coop/catan-web#442]
> 매번 그러진 않았지만 멘션 알림 하나가 알림창 중 멘션란에 뜨지 않는 것 같더라고요. 직접 멘션을 했음에도 멘션창에 뜨지 않는 경우도 있는걸까요? 사진 첨부한 씽님의 멘션이 제 멘션 알림창에 안뜨더라구요. (시간 기준으로 찾아본 결과) 다만 시간 기준으로 찾았을때 전체 알림창에서는 떠요!

https://parti.xyz/comments/82710

**Comment by dalikim** [comment]
분석해보니 이런 버그가 있네요.

예를 들께요.

1. 이레님이 오르그 채널에 모든 알림을 받도록 설정 
2. 씽님이 오르그 채널 게시물에 이레님 멘션 없이 댓글이 등록
3. 이레님께 알림 등록 ( 멘션아님 )
4. 씽님이 해당 댓글을 업데이트. 이레님과 소년님을 멘션으로 추가
5. 이미 알림이 가서 추가 등록 없음

파악은 이렇게 되었고요. 수정해 보겠습니다.

**Comment by dalikim** [comment]
@anne-parti @iamswain25 테스트서버 배포했는데 점검 한 번 하면 합니다. 내일 스탠드업에서 이야기 드릴께요.
