### ISSUE TITLE
이용약관(12,13조)을 변경합니다.

### ISSUE THREAD

**Issue by dongown** [parti-coop/catan-web#596]
약관 12조 5항과 13조 2항을 수정합니다(https://parti.xyz/terms)

[수정 요청 사항]
제 12조 서비스 이용의 중지 및 해지
<이전>
5) 회사는 회원이 계속해서 3개월 이상 로그인하지 않는 경우, 회원정보의 보호 및 운영의 효율성을 위해 이용을 제한할 수 있습니다.
<이후>
5) 회사는 일정기간 동안 서비스를 이용하지 않는 경우, 회원정보의 보호 및 운영의 효율성을 위해 이용을 제한할 수 있습니다.
① 회원이 계속해서 3개월 이상 로그인하지 않는 경우.
② 그룹에 1년 이상 새로운 게시물이 등록되지 않는 경우.

제 13조 권리의 귀속 및 저작물의 이용
<이전>
2) 게시물 등은 빠띠 혹은 그룹 오거나이저가 운영하는 인터넷 사이트 및 모바일 어플리케이션을 통해 노출될 수 있으며, 검색결과 내지 관련 프로모션 등에도 노출될 수 있습니다. 해당 노출을 위해 필요한 범위 내에서는 일부 수정, 복제, 편집되어 게시될 수 있습니다. 이 경우, 회사는 저작권법 규정을 준수하며, 회원은 언제든지 이메일 또는 각 서비스 내 관리기능을 통해 해당 게시물 등에 대해 삭제, 검색결과 제외, 비공개 등의 조치를 취할 수 있습니다.
<이후>
2) 게시물 등은 빠띠 혹은 그룹 오거나이저가 운영하는 인터넷 사이트 및 모바일 어플리케이션을 통해 노출될 수 있으며, 검색결과 내지 관련 프로모션 등에도 노출될 수 있습니다. 해당 노출을 위해 필요한 범위 내에서는 일부 수정, 복제, 편집되어 게시될 수 있습니다. 이 경우, 회사는 저작권법 규정을 준수하며, 회원은 언제든지 이메일 또는 각 서비스 내 관리기능을 통해 해당 게시물 등에 대해 삭제, 검색결과 제외, 비공개 등의 조치를 취하거나 요청할 수 있습니다.

- 실서버 배포 일정 확인한 뒤에, 회원들에게 약관 변경 안내를 할 예정입니다.

**Comment by dongown** [comment]
@jjuwoo 제 13조 약관 수정이 필요합니다.

'회원은 언제든지 이메일 또는 각 서비스 내 관리기능을 통해 해당 게시물 등에 대해 삭제, 검색결과 제외, 비공개 등의 조치를 취하거나 요청할 수 있습니다.'

저희가 의도했던 것은 <회사가 게시물 등에 대해 조치를 취하거나, 회원이 조치를 요청할 수 있다> 인데, 회원만 할 수 있다고 적었네요.

--> **회사는** 언제든지 이메일 또는 각 서비스 내 관리기능을 통해 해당 게시물 등에 대해 삭제, 검색결과 제외, 비공개 등의 조치를 취하거나 **회원은 이를** 요청할 수 있습니다.

라고 수정하면 어떨까 싶어요.

**Comment by jjuwoo** [comment]
> @jjuwoo 제 13조 약관 수정이 필요합니다.
> 
> '회원은 언제든지 이메일 또는 각 서비스 내 관리기능을 통해 해당 게시물 등에 대해 삭제, 검색결과 제외, 비공개 등의 조치를 취하거나 요청할 수 있습니다.'
> 
> 저희가 의도했던 것은 <회사가 게시물 등에 대해 조치를 취하거나, 회원이 조치를 요청할 수 있다> 인데, 회원만 할 수 있다고 적었네요.
> 
> --> **_회사는_** 언제든지 이메일 또는 각 서비스 내 관리기능을 통해 해당 게시물 등에 대해 삭제, 검색결과 제외, 비공개 등의 조치를 취하거나 **_회원은 이를_** 요청할 수 있습니다.
> 
> 라고 수정하면 어떨까 싶어요.

13조는 저작물 이용에 관련된 부분인데요.
빠띠가 믹스에 올라온 게시물을 사용할 수 있고, 이 경우 저작권법 규정을 준수하겠다. 회원은 사용된 게시물에 대해 삭제, 검색결과 제외, 비공개 등의 조치를 취하거나 요청할 수 있다. (빠띠 관리자에게) 입니다.

빠띠가 회원의 게시물에 대한 처리를 하겠다 부분은 
12조에 5항 에 작성한 것인데요.
일정기간 동안 서비스를 이용하지 않는 경우, 회원정보의 보호 및 운영의 효율성을 위해 이용을 제한하겠다

빠띠가 요청받지 않은 회원의 게시물을 삭제하거나 검색결과에서 제외, 비공개 처리할 일이 있나요?

**Comment by dongown** [comment]
> 빠띠가 요청받지 않은 회원의 게시물을 삭제하거나 검색결과에서 제외, 비공개 처리할 일이 있나요?

이 부분을 이야기하고자 하는 것은 아니고, 약관 문장 자체가 어색한 듯 싶어서요. 

'회원은 ~ 조치를 취하거나 요청할 수 있다' 에서 회원이 사용된 게시물에 대해 직접 조치를 취하는 것은 불가능하지 않나요? '회원이 사용된 게시물에 대해 조치를 취하도록 빠띠 관리자에게 요청할 수 있다.' 가 맞는 듯 합니다.

처음에 제가 제안했던 것도 살짝 잘못 생각했네요.

**Comment by jjuwoo** [comment]
게시물을 삭제하거나 숨김처리 할 수 있다 하셨던것 같은데요. 
불가능 하다면 아래와 같이 수정해도 될것 같습니다. 

2) 게시물 등은 빠띠 혹은 그룹 오거나이저가 운영하는 인터넷 사이트 및 모바일 어플리케이션을 통해 노출될 수 있으며, 검색결과 내지 관련 프로모션 등에도 노출될 수 있습니다. 해당 노출을 위해 필요한 범위 내에서는 일부 수정, 복제, 편집되어 게시될 수 있습니다. 이 경우, 회사는 저작권법 규정을 준수하며, 회원은 언제든지 이메일 또는 각 서비스 내 관리기능을 통해 해당 게시물 등에 대해 삭제, 검색결과 제외, 비공개 등의 조치를 ~취하거나~ 요청할 수 있습니다.

해당 노출을 위해 필요한 범위 내에서는 일부 수정, 복제, 편집되어 게시될 수 있습니다. 이 경우, = 회사가 글을 등록 한 경우 이기때문에
`회사는 언제든지 이메일 또는 각 서비스 내 관리기능을 통해 해당 게시물 등에 대해 삭제, 검색결과 제외, 비공개 등의 조치를 취하거나` 
위 내용을 쓸 필요가 없습니다.

**Comment by dongown** [comment]
네네 좋습니다 :)

**약관 최종안**
[수정 요청 사항]
제 12조 서비스 이용의 중지 및 해지
<이전>
5) 회사는 회원이 계속해서 3개월 이상 로그인하지 않는 경우, 회원정보의 보호 및 운영의 효율성을 위해 이용을 제한할 수 있습니다.
<이후>
5) 회사는 일정기간 동안 서비스를 이용하지 않는 경우, 회원정보의 보호 및 운영의 효율성을 위해 이용을 제한할 수 있습니다.
① 회원이 계속해서 3개월 이상 로그인하지 않는 경우.
② 그룹에 1년 이상 새로운 게시물이 등록되지 않는 경우.

제 13조 권리의 귀속 및 저작물의 이용
<이전>
2) 게시물 등은 빠띠 혹은 그룹 오거나이저가 운영하는 인터넷 사이트 및 모바일 어플리케이션을 통해 노출될 수 있으며, 검색결과 내지 관련 프로모션 등에도 노출될 수 있습니다. 해당 노출을 위해 필요한 범위 내에서는 일부 수정, 복제, 편집되어 게시될 수 있습니다. 이 경우, 회사는 저작권법 규정을 준수하며, 회원은 언제든지 이메일 또는 각 서비스 내 관리기능을 통해 해당 게시물 등에 대해 삭제, 검색결과 제외, 비공개 등의 조치를 취할 수 있습니다.
<이후>
2) 게시물 등은 빠띠 혹은 그룹 오거나이저가 운영하는 인터넷 사이트 및 모바일 어플리케이션을 통해 노출될 수 있으며, 검색결과 내지 관련 프로모션 등에도 노출될 수 있습니다. 해당 노출을 위해 필요한 범위 내에서는 일부 수정, 복제, 편집되어 게시될 수 있습니다. 이 경우, 회사는 저작권법 규정을 준수하며, 회원은 언제든지 이메일 또는 각 서비스 내 관리기능을 통해 해당 게시물 등에 대해 삭제, 검색결과 제외, 비공개 등의 조치를 요청할 수 있습니다.

**Comment by dongown** [comment]
@wagurano 추가 요청사항 남깁니다.

이용약관(https://parti.xyz/terms) 하단 **적용 일자**와, **이전 이용약관**도 함께 수정해야 합니다.
현재의 수정 반영 전 이용약관을 버전 2로 만들어야 합니다.

[현재]
적용 일자 : 2020년 7월 12일

이전 이용약관
- 버전 1(https://parti.xyz/terms/v1)

[수정 요청]
적용 일자: 2022년 4월 17일

이전 이용약관
- 버전 1 (최초 시작일 ~ 2020년 7월 12일)
- 버전 2 (2020년 7월 12일 ~ 2022년 4월 16일)

**Comment by dalikim** [comment]
@dongown 이 이슈를 지금 봤네요. 무튼 제가 이걸 보지 못하고 긴급 작업은 했습니다.

**Comment by dongown** [comment]
@dalikim 네네 이상 없습니다(저는 확인하시고 배포해주신 줄 알았네요😅)
